include:
  - ../mysql/docker-compose.yaml
  - ../nginx/docker-compose.yaml

services:
  api:
    build: .
    command: ./.docker/start.sh
    container_name: api
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=mysql
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/api
    depends_on:
        - mysql

  mysql:
    extends:
      file: ../mysql/docker-compose.yaml
      service: mysql