# include:
#   - ../mysql/docker-compose.yaml
#   - ../nginx/docker-compose.yaml

services:
  api:
    build: .
    command: ./.docker/start.sh
    container_name: api
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=mysql
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/api
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE_NAME=mysql
    ports:
      - 3306:3306
    volumes:
      - .:/home/node/api/mysql